# BUILD
FROM golang:1.21-alpine AS build

WORKDIR /app

COPY . .

RUN go mod tidy

WORKDIR /app/cmd/fetcher
RUN go build -o marksync

# RUN IMAGE
FROM alpine
WORKDIR /app
COPY --from=build /app/cmd/fetcher/fetcher .

CMD ["./fetcher"]