# BUILD
FROM golang:1.21-alpine AS build

WORKDIR /app

COPY . .

RUN go mod tidy

WORKDIR /app/cmd/tele
RUN go build -o telebot

# RUN IMAGE
FROM alpine
WORKDIR /app
COPY --from=build /app/cmd/tele/telebot .

CMD ["./telebot"]